
services:
  postgres:
    image: postgres:latest
    container_name: postgres_migrations
    restart: always
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: password
      POSTGRES_DB: migration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: